" Disable vi compatibility
set nocompatible


" Pathogen initialization
" =======================
filetype on
filetype off
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()


" Editing
" =======

" Enable syntax highlighting
syntax enable

" Enable indentation option based on file type
filetype plugin indent on

" Expand tab to spaces
set expandtab

" Set indent space
set tabstop=2
set shiftwidth=2
set softtabstop=2

" Make backspace behave as usual
set backspace=indent,eol,start

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
au ColorScheme * highlight ExtraWhitespace guibg=red
au BufEnter * match ExtraWhitespace /\s\+$/
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhiteSpace /\s\+$/

" No backup file
set nobackup

" Display line number
set number

" Enable ruler
set ruler

" Enable incremental searches
set incsearch

" Highlight search pattern matches
set hlsearch

" Show key command
set showcmd

" Show matching parentheses
set showmatch
set matchtime=3

" Show current mode
set showmode

" Substitutes globally by default
"   :%s/foo/bar/g <- g can be ommitted
set gdefault

" Key mappings
" ============

" Change <leader> key, default is \
let mapleader=","

" Hide search highlight
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" String all trailing whitespace in the current file
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" NERD Tree
nmap <silent> <F7> :NERDTreeToggle<CR>

" Taglist
nmap <silent> <F6> :TlistToggle<CR>

" Scratch
nnoremap <leader><tab> :tablast<CR>:tabnew<CR>:Scratch<CR>

" Script & Misc options
" =====================

set tags+=~/.vim/tags/cpp

" NERD Tree
let NERDTreeQuitOnOpen=1
let NERDTreeHighlightCursorLine=1

" SuperTab
let g:SuperTabDefaultCompletionType="context"
let g:SuperTabContextDefaultCompletionType="<c-x><c-n>"
let g:SuperTabLongestHighlight=1

" OmniCPPComplete
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_ShowPrototypeInAbbr = 1 " show function parameters
let OmniCpp_MayCompleteDot = 1 " autocomplete after .
let OmniCpp_MayCompleteArrow = 1 " autocomplete after ->
let OmniCpp_MayCompleteScope = 1 " autocomplete after ::
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]
" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

" GUI options
" ===========

if has('gui_running')
  colors blackboard

  " Show a colored column at column 81
  set colorcolumn=81

  " Set font name and size
  " Note: in macvim the format is Consolas:h11
  set guifont=Consolas\ 11
  set guicursor=a:blinkon0,i:ver1-blinkon0
  set columns=87
  set lines=26

  " Remove toolbar
  set guioptions-=T

  " Expand syntax list menu
  let do_syntax_sel_menu = 1|runtime! synmenu.vim|aunmenu &Syntax.&Show\ filetypes\ in\ menu
endif
